CREATE TABLE training_maxes (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  exercise TEXT CHECK( exercise IN ('OVERHEAD_PRESS','SQUAT','BENCH_PRESS','DEADLIFT') ) NOT NULL,
  training_max_weight TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users (id)
)
