CREATE TABLE skipped_weeks (
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  week_number INTEGER NOT NULL,
  iteration_number INTEGER NOT NULL,
  note TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
